version: '3'

services:
  mysql:
    image: mysql:8.0.11
    container_name: mysql
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./nextpage-db/mysql:/usr/src/mysql

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./nextpage-db/neo4j/data:/data
      - ./nextpage-db/neo4j/logs:/logs

  backend:
    # FIXME: 프로젝트 루트경로기준으로 수정해야함.
    build:
      context: .
      args:
          DJANGO_ALLOWED_HOSTS: “*”
          DJANGO_SECRET_KEY: “*”
          DJANGO_CORS_ORIGIN_WHITELIST: “*”
    container_name: django
    # command : 컨테이너가 띄워질 때 실행하는 명령어 / 서버실행
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - neo4j

volumes:
  nextpage-db: