#filebeat.inputs:
#  - type: log
#    paths:
#      - /var/lib/docker/containers/*/*.log
#    json.message_key: log.message
#    json.keys_under_root: true
#output.logstash:
#  hosts: ["logstash:5000"]
filebeat.inputs:
- type: log
  paths:
    - /var/log/nginx/*.log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"
