name: Django CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        setup-python-path: true
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate
    - name: Run Tests
      run: python manage.py test
#      env:
#        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
#        DATABASE_USER: ${{ secrets.DATABASE_USER }}
#        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
#        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
#        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
#        DATABASE_URL: ${{ secrets.DATABASE_URL }}
#        SECRET_KEY: ${{ secrets.SECRET_KEY }}
#      run: |
#        python manage.py test
